version: "3.8"
services:
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  client:
    image: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"